import "./globals.css";
import HeaderNav from "@/components/HeaderNav";

export const metadata = {
  title: "Alemeno",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-Body`}>
        <HeaderNav/>
        <div className="mt-10">
          {children}
        </div>
      </body>
    </html>
  );
}
